apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: discovery
  name: discovery
spec:
  ports:
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    io.kompose.service: discovery

