apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: orm
  name: orm
spec:
  ports:
  - name: "5431"
    port: 5431
    targetPort: 5431
  selector:
    io.kompose.service: orm
status:
  loadBalancer: {}
