apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: orm
  name: orm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orm
  template:
    metadata:
      labels:
        io.kompose.service: orm
    spec:
      containers:
      - image: microservices-example-kube_orm:latest
        imagePullPolicy: "IfNotPresent"
        name: orm
        ports:
        - containerPort: 5431
          hostPort: 5431
        resources: {}
      restartPolicy: Always

