apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: prod
  name: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prod
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: prod
    spec:
      containers:
      - env:
        - name: kafka
          value: kafka
        image: microservices-example-kube_prod:latest
        imagePullPolicy: "IfNotPresent"
        name: prod
        ports:
        - containerPort: 8080
          hostPort: 8080
        resources: {}
      restartPolicy: Always

