apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: querier
  name: querier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: querier
  template:
    metadata:
      labels:
        io.kompose.service: querier
    spec:
      containers:
      - env:
        - name: API_HOST
          value: orm
        image: microservices-example-kube_querier:latest
        imagePullPolicy: "IfNotPresent"
        name: querier
        ports:
        - containerPort: 8081
          hostPort: 8081
        resources: {}
      restartPolicy: Always

