apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: querier
  name: querier
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: querier
