apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    io.kompose.service: ui
  externalTrafficPolicy: Local 
  type: LoadBalancer
status:
  loadBalancer: {}
